# Anchore configuration file

#
# anchore_data_dir: <default is $HOME/.anchore/>
# anchore_db_driver: 'anchore_image_db_fs'
#
# tmpdir: '/tmp'
# log_file: '/var/log/anchore.log'
# debug_log_file: '/var/log/anchore_debug.log'
#
# image_data_store: 'data/'
#
# docker_conn: 'unix://var/run/docker.sock'
# docker_conn_timeout: '120'
#
# anchore_auth_conn_timeout: '5'
# anchore_auth_max_retries: '3'
# anchore_client_url: 'https://ancho.re/v1/account/users'
# anchore_token_url: 'https://ancho.re/oauth/token'
#
# feeds_url: 'https://ancho.re/v1/service/feeds'
# feeds_conn_timeout: '10'
# feeds_conn_max_retries: '3'
#
